#!/usr/bin/env python3

# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the RMTC Project

import argparse
import glob
import json
import os

# This script checks the inferences generated by the MNIST model and
# outputs the success rate.

# Example usage:
# ./validate_mnist_inferences.py --folder ./results

parser = argparse.ArgumentParser(
    description="Script that validates the inferences generated by the MNIST model."
)
parser.add_argument(
    "--folder", 
    type=str,
    help="Directory containing inferences generated by example_mnist_train.py"
)
args = parser.parse_args()


###############################################################################

def convert_logits_to_int(logits):
    """Convert a list of logits to an integer value.

    Args:
        logits (list<int>): List of 10 float values
    
    Returns:
        int: The corresponding integer value
    """
    max_value = max(logits)
    max_index = logits.index(max_value)
    return int(max_index)


def get_inferred_mnist_data(directory_path):
    """Generator that yields MNIST labels and predictions from inferred JSON files.

    Args:
        directory_path (str): Directory containing inferred JSON files

    Yields:
        list<Tuples(int, int)>: List of (label, prediction)
    """

    # Recursively get json files
    json_pattern = os.path.join(directory_path, "**", "*.json")
    json_files = glob.glob(json_pattern, recursive=True)

    for file_path in json_files:
        # The last digit in the file name is the label
        label = int(file_path.split("_")[-1].split(".")[0])
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            values = [0] * len(data.items())
            for key, value in data.items():
                values[int(key)] = float(value)
            yield (label, convert_logits_to_int(values))


def get_prediction_success_rate(directory_path):
    """Get the success rate of MNIST predictions as a percentage.

    Args:
        directory_path (str): Directory containing inferred JSON files

    Returns:
        Tuple of (float, int): (Percentage of correct predictions, num predictions)
    """
    total = 0
    success = 0
    for label, prediction in get_inferred_mnist_data(directory_path):
        total += 1
        if label == prediction:
            success += 1
    return success / total * 100, total

success, total = get_prediction_success_rate(args.folder)

print("Number of predictions: {}".format(total))
print("Prediction success rate: {:.2f}%".format(success))
